In [16]:
import pandas as pd 

# Loading and printing the 
df = pd.read_csv("Pokemon.csv")
print("Shape:", df.shape)
df.head()

Shape: (800, 13)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [17]:
# Handling duplicates
# The ID column just repeats for all the duplicates of the pokemon
# Use Name instead to check for duplicates
# Keep only the first occurrence of each Pokédex number
df_clean = df.drop_duplicates(subset="#", keep="first")

# Save the cleaned dataset
df_clean.to_csv("cleaned_pokemon.csv", index=False)

print(f"Original rows: {len(df)}")
print(f"Cleaned rows: {len(df_clean)}")
print("Cleaned dataset saved as 'cleaned_pokemon.csv'")

Original rows: 800
Cleaned rows: 721
Cleaned dataset saved as 'cleaned_pokemon.csv'

In [18]:
# Extracting the 7 numeric columns that will be used as model inputs 

feature_cols = ["Total", "HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed"]
X = df_clean[feature_cols].copy()

print("X shape:", X.shape)
X.head()

X shape: (721, 7)

   Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
0    318  45      49       49       65       65     45
1    405  60      62       63       80       80     60
2    525  80      82       83      100      100     80
4    309  39      52       43       60       50     65
5    405  58      64       58       80       65     80

In [19]:
# Extracting Legendary column and converting it to numeric (1 = Legendary, 0 = not)

y = df_clean["Legendary"].astype(int)

print()

In [20]:
# Check for missing values in X or y if there are any 

print("Missing values in X:")
print(X.isna().sum())
print("\nMissing values in y:", y.isna().sum())

Missing values in X:
Total      0
HP         0
Attack     0
Defense    0
Sp. Atk    0
Sp. Def    0
Speed      0
dtype: int64

Missing values in y: 0

In [21]:
# Saving cleaned data
X.to_csv("X_clean.csv", index=False)
y.to_csv("y_clean.csv", index=False)

print("Saved X_clean.csv and y_clean.csv")
print(f"Final dataset: {X.shape[0]} rows, {X.shape[1]} features, {y.sum()} Legendary")

Saved X_clean.csv and y_clean.csv
Final dataset: 721 rows, 7 features, 46 Legendary